# 线性代数

### 1.距阵创建

In [14]:
import torch
x = torch.arange(20).reshape(5, 4)
print(x);
# len 返回的是第一个维度的大小
print(len(x))
# 距阵的转置
print(x.T)
# 创建一个副本
y = x.clone()
print(x + y)
print(x * y)
# x.sum 和 sum(x) 不一样
print(x.sum())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
5
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])
tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38]])
tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])
tensor(190)


### 2.矩阵求和

In [ ]:
import torch
x = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
print(x)
# x.sum 和 sum(x) 不一样
# sum(x) 按行求和
print(x.sum())
print(sum(x))
# axis=0 指的是沿着第0维（最外层维度2）进行求和
x_sum_axiso0 = x.sum(axis=0)
print(x_sum_axiso0)
# axis=1 指的是沿着第1维（3）进行求和，结果是 (2, 4)
x_sum_axiso1 = x.sum(axis=1)
print(x_sum_axiso1)
# axis=[0, 1] 指的是沿着第0维和第1维进行求和，结果是 (4)
x_sum_axiso = x.sum(axis=[0, 1])
print(x_sum_axiso)
# 不丢掉维度，可以用广播机制
# keepdims=True 求和的那个轴会被保留为1的维度，因此形状变成 (2, 1, 4)
sum_x = x.sum(axis=1, keepdims=True)
print(sum_x)
print(x / sum_x)
# 按第0维进行累加求和
print(x.cumsum(axis=0))

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
tensor(276.)
tensor([[12., 14., 16., 18.],
        [20., 22., 24., 26.],
        [28., 30., 32., 34.]])
tensor([[12., 14., 16., 18.],
        [20., 22., 24., 26.],
        [28., 30., 32., 34.]])
tensor([[12., 15., 18., 21.],
        [48., 51., 54., 57.]])
tensor([60., 66., 72., 78.])
tensor([[[12., 15., 18., 21.]],

        [[48., 51., 54., 57.]]])
tensor([[[0.0000, 0.0667, 0.1111, 0.1429],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.6667, 0.6000, 0.5556, 0.5238]],

        [[0.2500, 0.2549, 0.2593, 0.2632],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.4167, 0.4118, 0.4074, 0.4035]]])
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 14., 16., 18.],
         [20., 22., 24., 26.],
         [28., 30., 32., 34.]]])


### 3.平均值

In [30]:
import torch
x = torch.arange(40, dtype=torch.float32).reshape(2, 5, 4)
print(x)
# mean() 等同于 x.sum() / x.numel()
# mean() 方法要求输入为浮点类型或复数类型
print(x.mean())
# mean(axis=0) 等同于 x.sum(axis=0) / x.shape[0]
print(x.mean(axis=0))

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])
tensor(19.5000)
tensor([[10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.],
        [22., 23., 24., 25.],
        [26., 27., 28., 29.]])


### 4.距阵乘积

In [68]:
import torch
# 一维张量它没有明确的行或者列。
x = torch.arange(4, dtype=torch.float32)
y = torch.arange(4, dtype=torch.float32)
z = torch.arange(12, dtype=torch.float32).reshape(3, 4)
a = torch.ones(4, 2)
print(x)
# 点积也可以先按元素乘，再求和
print(torch.dot(x, y))
print(torch.sum(x * y))
# 矩阵向量积，先写距阵，后写一维张量
print(torch.mv(z, x))
# 距阵乘距阵
print(torch.mm(z, a))

tensor([0., 1., 2., 3.])
tensor(14.)
tensor(14.)
tensor([14., 38., 62.])
tensor([[ 6.,  6.],
        [22., 22.],
        [38., 38.]])


### 5.范数

In [72]:
import torch
x = torch.tensor([3.0, -4.0])
# 范数是向量元素平方和的平方根
print(torch.norm(x))
# L1范数是向量元素的绝对值之和，abs 是绝对值
print(torch.abs(x).sum())
# 距阵的F范数是距阵元素的平方和的平方根
y = torch.ones((4, 9))
print(torch.norm(y))

tensor(5.)
tensor(7.)
tensor(6.)
