# 自动求导

### 1.$Y = 2 X^T X$

In [11]:
import torch
x = torch.arange(4.0)
print(x)
# 将梯度存在 x.grad, 默认是None
x.requires_grad_(True)
print(x.grad)
# 计算 y, dot 一维向量做内积
# grad_fn=<MulBackward0> 记录是怎么算出来的
y = 2 * torch.dot(x, x)
print(y)
# 调用反向函数自动计算 y 关于 x 每一个分量的梯度
y.backward()
print(x.grad)
print(x.grad == 4 * x)
# 默认情况 pytorch 会累积梯度，需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
print(x.grad)

tensor([0., 1., 2., 3.])
None
tensor(28., grad_fn=<MulBackward0>)
tensor([ 0.,  4.,  8., 12.])
tensor([True, True, True, True])
tensor([1., 1., 1., 1.])


### 2.$Y = X.sum()$

In [12]:
# 默认情况 pytorch 会累积梯度，需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
print(x.grad)

tensor([1., 1., 1., 1.])


### 3.$Y = X * X$

In [20]:
# 前两种情况 y 都是标量，这种情况 y 是非标量
x.grad.zero_()
y = x * x
# 先求和再求导
y.sum().backward()
print(x.grad)
print(x.grad == 2 * x)
# y.detach() 会返回一个与 y 数据相同，但脱离计算图的新张量
# 相当于常数
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
print(x.grad == u)

tensor([0., 2., 4., 6.])
tensor([True, True, True, True])
tensor([True, True, True, True])
