# 数据操作，数据预处理

## 一、数据操作

### 1. 初始化

In [ ]:
import torch
# x 是张量，表示一个数值组成的数组，可以是多维数组
x = torch.arange(12)
print(x)
# shap 输出张量的形状
print(x.shape)
# numel 输出张量的元素个数
print(x.numel())
# reshape 可以改变张量的形状，不改变元素数量和值
print(x.reshape(3, 4))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [ ]:
import torch
# zeros 创建一个2行3列4通道的全零张量
x = torch.zeros(2, 3, 4)
print(x)
# ones 创建一个2行3列4通道的全一张量
# 2个矩阵，每个矩阵3行，每行4个元素
y = torch.ones(2, 3, 4)
print(y)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [ ]:
import torch
# 为张量中的每个元素赋予确定值
x = torch.tensor([[2, 1, 4, 3],[1, 2, 3, 4],[4, 3, 2, 1]])
print(x)

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


### 2.运算

In [ ]:
import torch
# 各元素对应加减乘除，取余
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
# **是各元素对应求幂（1.0^2）
print(x**y)
# torch.exp是以 e 为底 x 为指数的指数运算
print(torch.exp(x))
# 逻辑运算符构建张量
print(x == y)
# 对张量中所有元素进行求和，产生只有一个元素的张量
print(x.sum())

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([1., 0., 0., 0.])
tensor([ 1.,  4., 16., 64.])
tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])
tensor([False,  True, False, False])
tensor(15.)


### 3.拼接


In [ ]:
import torch
# dtype=torch.float32 强制为浮点型
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
y = torch.tensor([[2.0, 1, 4, 3],[1, 2, 3, 4],[4, 3, 2, 1]])
# dim=0 是按行拼，dim=1 是按列拼
print(torch.cat((x, y), dim=0))
print(torch.cat((x, y), dim=1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


### 4.广播机制


In [ ]:
import torch
x = torch.arange(3).reshape((3, 1))
y = torch.arange(2).reshape((1, 2))
print(x)
print(y)
# 维度一样，形状不一样的，将自己复制成相同大小再相加
# x 要先复制一列，y 要复制两行
print(x+y)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


### 5.元素增删改查

In [34]:
import torch
x = torch.arange(12).reshape((3, 4))
# -1代表最后一个元素
print(x[-1])
# 左闭右开
print(x[1:3])
# 赋值
x[1, 2] = 999
print(x)
# :可以省略，不省更规范
x[0:2, :] = 999
print(x)

tensor([ 8,  9, 10, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[  0,   1,   2,   3],
        [  4,   5, 999,   7],
        [  8,   9,  10,  11]])
tensor([[999, 999, 999, 999],
        [999, 999, 999, 999],
        [  8,   9,  10,  11]])


### 6.关于内存

In [ ]:
import torch
x = torch.arange(3).reshape((3, 1))
y = torch.arange(2).reshape((1, 2))
# id 表示的是占的内存位置
before = id(y)
y = y + x
#加完y的内存位置就变了
print(id(y) == before)
before = id(y)
# 用y += x，x[:]=x+y，对应的内存位置不会改变
y += x
print(id(y) == before)
# 原地操作, 创建一个和 y 形状一样的全零张量 z
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y;
print('id(z):', id(z))

False
True
id(z): 2352632015104
id(z): 2352632015104


### 7.张量类型转换

In [ ]:
import torch
# pytorch 是深度学习框架的核心数据结构，用于构建神经网络、自动求导、GPU 加速
x = torch.arange(3).reshape((3, 1))
# numpy 是科学计算的基础数据结构，几乎所有数据处理、数值分析库都基于它
a = x.numpy()
print(type(a))
print(type(x))
# 大小为1的张量可以转换为标量
a = torch.tensor([3.5])
print(a)
print(float(a))
print(int(a))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
tensor([3.5000])
3.5
3


## 二、数据预处理

### 1.创建一个人工数据集，存储在csv文件中

In [ ]:
import os
# '..' 表示当前目录的上一级目录（父目录），'data' 是一个文件夹名
# ../data，也就是在父目录里创建一个叫 data 的文件夹。
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
# 存储在house_tiny.csv文件中，完整路径是：../data/house_tiny.csv
data_file = os.path.join('..', 'data', 'house_tiny.csv')
# data_file 就代表了 CSV 文件的位置
# w，写入模式打开指定的文件
with open(data_file, 'w') as f:
    # 列名，房间数量，小巷，价格
    f.write('NumRooms,Alley,Price\n')
    # 每行是一个数据样本（pave 是有小巷）
    # 'NA'、'null'、'N/A' 等识别为缺失值
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

### 2.从创建的csv文件中加载原始数据集

In [ ]:
import pandas as pd
# 读取文件
data = pd.read_csv(data_file)
print(data)
# 不用 print 是 html 表格形式
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


,NumRooms,Alley,Price
0,NaN,Pave,127500
1,2.0,NaN,106000
2,4.0,NaN,178100
3,NaN,NaN,140000


### 3.处理缺失数据（插值和删除）

In [83]:
# 删除就是直接丢掉
# 插值
# data.iloc[:, 0:2] 给了 inputs，data.iloc[:, 2] 给了 outputs
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
# 数值部分，缺失值用均值填充
inputs['NumRooms'] = inputs['NumRooms'].fillna(inputs['NumRooms'].mean())
print(inputs)
# 类别值或离散值部分，转换为独热编码
# True 和 False 转换为整数
inputs = pd.get_dummies(inputs, dummy_na=True, dtype=int)
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN
   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


### 4.转化为张量

In [84]:
import torch
x, y =  torch.tensor(inputs.values), torch.tensor(outputs.values)
print(x)
print(y)

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)
tensor([127500, 106000, 178100, 140000])
